logstashshipper:
    build: logstash
    volumes:
        - logs:/var/logs
        - conf/shipper:/etc/conf  
        - patterns:/etc/patterns  
    links: 
        - redisbroker:redis
redisbroker:
    image: redis
    ports:
        - "6379:6379"
logstashindexer:
    build: logstash
    volumes:
        - conf/indexer:/etc/conf
    links:
        - redisbroker:redis
        - elasticsearch
elasticsearch:
    build: elasticsearch
    ports: 
        - "9200:9200"
        - "9300:9300"
kibana:
    build: kibana
    ports:
        - "8888:8888"
